# Generated by Django 3.1.5 on 2021-02-14 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
