# Generated by Django 3.1.5 on 2021-03-13 16:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=40, verbose_name='заголовок статьи')),
                ('description', models.CharField(blank=True, max_length=150, verbose_name='описание статьи')),
                ('text', models.TextField(verbose_name='текст статьи')),
                ('time', models.DateTimeField(auto_now=True)),
                ('img', models.ImageField(blank=True, upload_to='images/', verbose_name='превью')),
                ('likes', models.ManyToManyField(blank=True, related_name='likes', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'статья',
                'verbose_name_plural': 'статьи',
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_data', models.ImageField(upload_to='photos')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='all_phots', to='main.article')),
            ],
            options={
                'verbose_name': 'Фотография',
                'verbose_name_plural': 'Фотографии',
            },
        ),
    ]
