# Generated by Django 3.1.5 on 2021-03-03 13:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0004_remove_article_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='likes',
            field=models.ManyToManyField(default='', related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
