# Generated by Django 3.1.5 on 2021-03-04 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_article_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='img',
        ),
        migrations.AddField(
            model_name='article',
            name='img_main',
            field=models.ImageField(blank=True, upload_to='images/', verbose_name='превью'),
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_data', models.ImageField(upload_to='photos')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='all_phots', to='main.article')),
            ],
            options={
                'verbose_name': 'Фотография',
                'verbose_name_plural': 'Фотографии',
            },
        ),
    ]
